version: 2.1
orb:
  aws-cli: circleci/aws-cli@3.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "hello world"
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #           --template-file template.yml \
  #           --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #           --region us-east-1
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["8c:40:96:93:71:73:04:42:44:08:21:72:80:ab:b2:a0"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Run playbook and configure server
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  doJobs:
    jobs:
      - build
      - configure_infrastructure